### ISSUE TITLE
R 3.6.2 / works with a pi4

### ISSUE THREAD

**Issue by rggefrm** [ArturKlauser/raspberrypi-rstudio#10]
First, I can confirm the rstudio-server works with buster running on a pi4 (4Gbyte). I have compiled R from source (3.6.2).
I had to force the install to overcome the dependency problems (because I do not have R installed from the debian archives),
Now I have dependencies errors because apt-get still tries to install R from the debian archives.
Could you build the server with R from source (3.6.2) ?

Frank

**Comment by ArturKlauser** [comment]
I'm not quite sure exactly what you're saying. Could you please clarify by adding more relevant information?
E.g. `apt-cache showpkg r-base rstudio` and any `apt-get` commands that are failing including their output.

**Comment by rggefrm** [comment]
Dear Artur,

I have build R from source to get the latest R version (3.6.2) installed in /opt/R-3.6.2

When I used the deb file I had to use —force-install Option with dpki, otherwise the R 3.5 would be installed from the Debian archives.

RStudio works, but apt-get install -f complains about the missing R 3.5 version.

Does my email makes sense? I’m sorry I’m not a software geek.

Best Wishes

Frank

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ArturKlauser** [comment]
Oh, I beg to disagree. If you have compiled and installed R from source you're a software geek ;)

But in order for me to help, you need to give me all the details. Your verbal description is not good enough.
I need to know the exact sequence of commands you used - copy and paste them into this issue - including the outputs of those commands. Annotate them with where you have expected something different to happen and what that expectation was. If I can't copy your commands to my terminal and get to the same error you have, I can't help.

**Comment by rggefrm** [comment]
Dear Artur,

I solved the problem.
I did

sudo apt --fix-install

and R (3.5) was installed. Then I installed rstudio-server from your site.
No error this time. I added

rsession-which-r=/opt/R/3.6.2/bin/R

to  /etc/rstudio/rserver.conf

when I now start http://<local address>:8787

than RStudio uses 3.6.2

I wish you all the best for coming new year.

Frank

PS: Do you know how to use the  https protocoll for the rstudio server?


Am Di., 31. Dez. 2019 um 17:35 Uhr schrieb Artur Klauser <
notifications@github.com>:

**Comment by ArturKlauser** [comment]
Glad you figured out your problem.
From the little information you gave I can only guess that you built and installed R circumventing your computer's packet management system (apt) and rather installed R binaries directly with `make install` or something of that sort. It probably would have made your life easier building the .deb package and properly installing that with apt, then your package manager would know that R is installed. There is nothing special about version 3.5 of R from the point of view of the rstudio-server .deb package. It just want some R package installed - any version > 2.10 will do.

In order to use https for the open source version of rstudio server you'll have to use a reverse proxy in front of rstudio. I haven't had the need to do it myself, but there are several instructions online on how to set up reverse proxies. [Here is one for nginx + rstudio server](https://www.linode.com/docs/development/r/how-to-deploy-rstudio-server-using-an-nginx-reverse-proxy/#set-up-the-reverse-proxy), but that is configured to use http (port 80), not https (port 443). There are others on how to set up https for nginx, in particular you want to look for some instructions that explain the certificate setup for https.

Happy 2020!

**Comment by rggefrm** [comment]
Many Thanks for your helpful thoughts.
I'm the underlying problem is the R source installation and the fact that
the package management system did not know about the installation. I
haven't build a deb package yet. However I will try in the next days to
pack it.
At least your rstudio-server packages saved me a lot of time building
rstudio from the source. I have done this in the past which I rather would
avoid it
Best Wishes

Frank

Am Mi., 1. Jan. 2020 um 08:41 Uhr schrieb Artur Klauser <
notifications@github.com>:
