### ISSUE TITLE
Support for Raspberry Pi 4?

### ISSUE THREAD

**Issue by bshor** [ArturKlauser/raspberrypi-rstudio#5]
Are there any difficulties installing this on the newest Raspberry Pi 4? I thought it would work much better with up to 4Gb RAM and a faster CPU.

**Comment by ArturKlauser** [comment]
I haven't tried it on a Pi 4, but since system architecture and OS environment hasn't changed from Pi 3 to Pi 4 it should work just fine, and you're certainly going to be happier with the 4GB of RAM on it. I'm assuming you're running the current Raspbian based on Debian 10 (Buster)?
```
(. /etc/os-release; echo $PRETTY_NAME)
Raspbian GNU/Linux 10 (buster)
```
In that case, if you want to install natively, installing the packages built for **buster** should work fine.
If you want to run the server inside the docker image then you can run any docker image.

BTW, I just released a new version (1.3.1) which fixes some package dependency issues for Buster. Make sure you use that one instead of the older 1.3.0.

Let me know how it goes.

**Comment by bshor** [comment]
Thanks! Don't have it installed yet, but I will let you know what happens when I do.

**Comment by ArturKlauser** [comment]
According to #10 it works fine on Raspberry Pi 4.
Closing now. If you run into any actual problems please open a new issue.
